{{/*
  PodMonitor configuration for Rocket.Chat metrics collection.
  In monolithic mode, Rocket.Chat exposes metrics on a single port named "metrics".
  In microservices mode:
  - The main rocketchat-rocketchat microservice exposes metrics on two ports:
    * "metrics" - for legacy metrics
    * "ms-metrics" - for microservices-specific metrics
  - Other microservices only expose metrics on the "ms-metrics" port
*/}}
{{- if and .Values.podMonitor.enabled .Values.prometheusScraping.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rocketchat.name" . }}
    helm.sh/chart: {{ include "rocketchat.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.podMonitor.interval | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rocketchat.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.microservices.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "rocketchat.fullname" . }}-ms
  labels:
    app.kubernetes.io/name: {{ include "rocketchat.name" . }}
    helm.sh/chart: {{ include "rocketchat.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podMetricsEndpoints:
    - port: ms-metrics
      interval: {{ .Values.podMonitor.interval | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rocketchat.name" . }}
{{- end }}
{{- end }}